### ISSUE TITLE
Add "Custom Tools" section to docs

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier#110]
Gladier explains what Clients and Tools are, but it doesn't show any usable code for people to create brand new ones. I think it would be especially useful to demo a snippet where a custom tool is used. Taking from the Gladier examples repo:

```

##Funcx defined function
def file_size(**data):
    """Return the size of a file"""
    import os
    return os.path.getsize(data['pathname'])

##Gladier tool abstraction
@generate_flow_definition
class FileSize(GladierBaseTool):
        funcx_functions = [file_size]

@generate_flow_definition
class Example_Client(GladierBaseClient):
    gladier_tools = [
        FileSize,
    ]
```

This is a nice copy-pastable example new users can use to start their own custom tools.

**Comment by ravescovi** [comment]
Yes. I think we are building a good base for things. Just need to figure
out all these repo's and what goes where.

**Comment by NickolausDS** [comment]
Added! https://gladier.readthedocs.io/en/latest/gladier/custom_tools.html
