### ISSUE TITLE
Investigate alerting on failed flows

### ISSUE THREAD

**Issue by ryanchard** [globus-gladier/gladier#165]
It would be nice if we could be alerted on a failed flow. To achieve this we likely need a condition following each tool to determine success and then either carry on or branch to an alert step.

**Comment by NickolausDS** [comment]
What kind of alerts would typical users like to have? I think the first indication that something went wrong is to simply check the flows webapp status page. A more active alert could be email.

**Comment by ryanchard** [comment]
I think email would be good. With thousands of flows the webapp could get a little difficult to constantly monitor. Perhaps this will be solved with a multi-flow view/dashboard.

**Comment by ravescovi** [comment]
Multi-flow dashboard would be nice but would require "nice" tagging.
Specially, when multiple experiments are running.
