### ISSUE TITLE
Conda package request

### ISSUE THREAD

**Issue by carterbox** [globus-gladier/gladier#203]
Could you please publish a conda package for gladier, gladier-tools, and dependencies on the conda-forge channel? You can do so by opening one PR at https://github.com/conda-forge/staged-recipes.

Most PYPI package metadata can be autoconverted into conda format using [grayskull](https://github.com/conda-incubator/grayskull). I can help, if needed.

**Comment by NickolausDS** [comment]
Thanks for posting this! I see how getting these packages onto the conda-forge channel would be useful. We'll look into it.
