### ISSUE TITLE
Create a Gladier website

### ISSUE THREAD

**Issue by ryanchard** [globus-gladier/gladier#5]
We want to stand up a website to help bootstrap people to use Flows for instrument analysis. Discussion on this is included in: https://docs.google.com/document/d/1kayOtBTowVYAcxERqKDeyMSGRNmiwndHsDeAsYgjCos/edit?usp=sharing

**Comment by ianfoster** [comment]
We have [https://github.com/ANL-Braid/braid/blob/main/index.md](https://github.com/ANL-Braid/braid/blob/main/index.md) now (publicly accessible at [https://anl-braid.github.io/braid/](https://anl-braid.github.io/braid/)). That in turn links to https://github.com/ANL-Braid/flows, which is not yet publicly accessible.

And we have [https://gladier.readthedocs.io](https://gladier.readthedocs.io). 

We also have the nice "Face" demo at [https://demo.gladier.org/gladier-demo/about/](https://demo.gladier.org/gladier-demo/about/). 

How do we integrate these all into a nice consistent whole?

**Comment by ravescovi** [comment]
We have now gladier.org and https://github.com/globus-gladier/gladier.org
We can condense most things into this website?
