### ISSUE TITLE
Feature: Add labels to runs, allow passing other args to run_flow

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier#96]
Currently, it isn't possible to pass arguments to `run_flow`. At the very least, we should allow passing through arguments to override values, including label. 

I think it would also be handy to implement a stub on Gladier called `get_label`, which would be a function automatically called by `run_flow` and passed the input dictionary for the given flow run. That way, each Gladier Client could be customized to show very specific information for a given flow run on the webapp dash page. I imagine it would look like this:

```
def get_label(self, flow_input):
    return f'{flow_input["experiment"]}: running CBF range: {flow_input["low"]}--{flow_input["high"]}'
```

**Comment by ravescovi** [comment]
where would get label live? inside the def Client(gladierBaseClient)?

**Comment by NickolausDS** [comment]
Yeah, it would be optional to define it within your subclass.

**Comment by ravescovi** [comment]
A potential problem is that the payload is not defined when the client
instance is first invoked.

**Comment by NickolausDS** [comment]
Something like:
```
class HelloGladier(GladierBaseClient):
    gladier_tools = [
        'gladier.tools.hello_world.HelloWorld',
    ]
    flow_definition = 'gladier.tools.hello_world.HelloWorld'

    def get_label(flow_input):
        return f'Say hello to {flow_input["entity"]}'
```

**Comment by NickolausDS** [comment]
`get_label` would be invoked automatically by the Gladier Client when `run_flow` is run by the user with a given set of flow_input.

**Comment by ravescovi** [comment]
Tha would be great but I would still create some error handling if the user
don't set 'entity'

**Comment by ravescovi** [comment]
The same needs to be done for Transfer/SmartTransfer.
That will clean the website experience.

**Comment by NickolausDS** [comment]
I think this is a rare circumstance where errors are ok, since the user should be aware of the input they're passing to a given flow and are responsible for the implementation of `get_label`. I think setting it should remain optional. 

We could set a default label if the user chooses not to implement `get_label`, but I'm not quite sure what to use. The flow title is already listed. We could pull the local time off the user's machine and list that? Something like `Hello World: Jan 1st, 2:23pm` Although the webapp already lists the time so I'm not sure that would be useful.

**Comment by ravescovi** [comment]
I think for undefined it is ok as is. Maybe a little more parsed but that
can be done on the server side.

**Comment by NickolausDS** [comment]
Added in #101
