### ISSUE TITLE
Add INFO section in beginning of docs to include flows/funcx tutorial. 

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier#98]
I think it might be useful to point people towards the Jupyter notebook for running flows, and the funcx tutorial for registering and running functions. That way people can learn the 'magic' of Gladier.

Would it also be useful to have a separate section that explains in detail how Gladier combines funcx + flows? Maybe by explaining how it automatically registers and stores funcx uuids, and generates/deploys/updates flow JSON.

**Comment by ravescovi** [comment]
yes. now that I've played with the globus automate example. Most likely we
want to have something like that.

**Comment by NickolausDS** [comment]
Added in #124
